# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


jobs:      
- job: DocFX

  pool:
    vmImage: 'vs2017-win2016'

  steps:
  - task: NuGetToolInstaller@1
    displayName: 'Use NuGet 5.1.0'
    inputs:
      versionSpec: 5.1.0
    
-  task: DownloadGitHubRelease@0
    inputs:
      connection: 'OCS Samples'
      userRepository: 'osisoft/Edge-Adapter'
      defaultVersionType: 'latest'
      downloadPath: '$(Build.SourcesDirectory)/V1/main)'
      
  - script: |
      dir
    workingDirectory:  '$(Build.SourcesDirectory)'
    displayName: 'rename config file1'

  - script: |
      dir
    workingDirectory:  '$(Build.SourcesDirectory)/V1/main'
    displayName: 'rename config file1'

  - script: |
      dir
    workingDirectory:  '$(Build.SourcesDirectory)'
    displayName: 'rename config file1'

  - script: |
      dir
    workingDirectory:  '$(Build.SourcesDirectory)/V1/main'
    displayName: 'rename config file1'


  - script: |
      git pull --recurse-submodules
    workingDirectory:  '$(Build.SourcesDirectory)'
    displayName: 'rename config file1'

  - script: |
      dir
    workingDirectory:  '$(Build.SourcesDirectory)'
    displayName: 'rename config file1'

  - script: |
      dir
    workingDirectory:  '$(Build.SourcesDirectory)/V1/main'
    displayName: 'rename config file1'

  - script: |
      choco install docfx
    workingDirectory:  '$(Build.SourcesDirectory)'
    displayName: 'rename config file1'


  - task: NuGetCommand@2
    displayName: 'Install docfx'
    inputs:
      command: custom
      arguments: 'install -ConfigFile .\NuGet.Config docfx.console -Version "2.43.2"'
