# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


jobs:      
- job: DocFX

  pool:
    vmImage: 'vs2017-win2016'

  steps:
  - task: NuGetToolInstaller@1
    displayName: 'Use NuGet 5.1.0'
    inputs:
      versionSpec: 5.1.0

  - task: NuGetCommand@2
    displayName: 'Install docfx'
    inputs:
      command: custom
      arguments: 'install -ConfigFile .\NuGet.Config docfx.console -Version "2.43.2"'

  - script: |
      dir
    workingDirectory:  '$(Build.SourcesDirectory)'
    displayName: 'rename config file1'

