# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

  pool:
    vmImage: 'vs2017-win2016'

  steps:
  - task: NuGetToolInstaller@1
    displayName: 'Use NuGet 5.1.0'
    inputs:
      versionSpec: 5.1.0

  - task: NuGetCommand@2
    displayName: 'Install docfx'
    inputs:
      command: custom
      arguments: 'install -ConfigFile .\NuGet.Config docfx.console -Version "2.43.2"'

  - powershell: |
    Get-ChildItem Env:
    
    # Checkout master and pull updates
    echo "doing checkout"
    git checkout origin/master
    
    echo "doing pull"
    git pull    
    
    displayName: 'Compile DocFX'

  - script: |
      del $(credfileoidcconfig)
    workingDirectory:  '$(Build.SourcesDirectory)$(configpath)/' 
    displayName: 'rename config file1'

